version: '3.8'

services:
  mcp-http-proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: github-mcp-server-local
    ports:
      - "3000:3000"
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - GITHUB_TOOLSETS=${GITHUB_TOOLSETS:-all}
      - GITHUB_DYNAMIC_TOOLSETS=${GITHUB_DYNAMIC_TOOLSETS:-0}
      - PORT=3000
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
